### ISSUE TITLE
Web deploy from Visual Studio

### ISSUE THREAD

**Issue by szilardd** [imranbaloch/ASPNETIdentityWithOnion#1]
Not related to the Onion architecture directly, but how do you deploy a project with this structure using the Publish feature in Visual Studio ? Or using another deploy approach ?

As the Web project has reference only to the Core, when you publish the project, the *.dll files and NuGet package referenced in the other projects are not deployed.

**Comment by imranbaloch** [comment]
Unfortunately Yes. You have to set every projects Build Path to Web/Bin From Project -> Properties. Then after BUILD copy deploy all bin dlls as well.

**Comment by szilardd** [comment]
I did just that, thanks. Found the solution here: http://stackoverflow.com/questions/2747081/how-do-you-include-additional-files-using-vs2010-web-deployment-packages
