### ISSUE TITLE
Security stamp not validated after update

### ISSUE THREAD

**Issue by florinsecal** [imranbaloch/ASPNETIdentityWithOnion#11]
- Login with same user from two different  browser
- Change password from one of the browsers or ApplicationUserManager.UpdateSecurityStampAsync(userId)
- SecurityStampValidator.OnValidateIdentity still validates the user (after validateInterval) from the other browser, although security stamp is different

**Comment by imranbaloch** [comment]
This is identity issue please add issue there https://aspnetidentity.codeplex.com/

**Comment by florinsecal** [comment]
I think a fix for that is adding:

```
app.CreatePerOwinContext(
                () => DependencyResolver.Current.GetService<UserManager<ApplicationIdentityUser, int>>());
```

to ConfigureAuth in Startup.Auth.cs. 

Security stamp is verified after.
