### ISSUE TITLE
Question about ApplicationUserManager

### ISSUE THREAD

**Issue by bringking** [imranbaloch/ASPNETIdentityWithOnion#2]
@imranbaloch , thanks for the great inspiration and architecture. I am new to Autofac, so I am having a little trouble. Everything seems to be working, however with the ApplicationUserManager implementation, I am getting -

```
 "exceptionMessage": "No constructors on type 'EGWC_Server.Identity.ApplicationUserManager' can be found with the constructor finder 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'.",
```

If I provided a parameter-less constructor for the ApplicationUserManager then the exception goes away, but then the context is not set. Any ideas here?

**Comment by abcplex** [comment]
May be I missed this question but this is AutoFac specfic issue.

**Comment by imranbaloch** [comment]
AutoFac specific issue.
