### ISSUE TITLE
Publish issue

### ISSUE THREAD

**Issue by snebjorn** [imranbaloch/ASPNETIdentityWithOnion#3]
Hi, do you have a solution for the "publishing issues" when using an outer dependency resolver layer?

Let me explain. When you publish a web project the process will only build the web project and its dependencies. Since the web project doesn't know about the bootstrapper it isn't build and so it isn't published - breaking the solution.

What I've done in the past is to just include the bootstrapper inside the web project as it's less of a pain even though it's not as correct.
I was hoping the new OWIN startup would solve this.

**Comment by imranbaloch** [comment]
See this issue,
https://github.com/imranbaloch/ASPNETIdentityWithOnion/issues/1

Also you can update your pubxml file,
http://www.asp.net/mvc/tutorials/deployment/visual-studio-web-deployment/deploying-extra-files

**Comment by snebjorn** [comment]
Fast response :+1: 

That was what I used to do as well, was hoping for a bit more automated process :)
Thank you.
