### ISSUE TITLE
Additional user profile properties

### ISSUE THREAD

**Issue by charanraj-golla** [imranbaloch/ASPNETIdentityWithOnion#5]
Hi Imran,
I tried adding more user properties by modifying the Appuser class but this is not being reflected in the table. If I add properties in ApplicationIdentityUser class the table includes those properties as columns. Is there any way in which I can just modify the POCO in the DomainModel Core project and the same would be taken as a additional column when the table is being created.

**Comment by imranbaloch** [comment]
You need to add migrations. See this lnk
http://www.asp.net/mvc/tutorials/mvc-5/create-an-aspnet-mvc-5-app-with-facebook-and-google-oauth2-and-openid-sign-on

**Comment by jjwilliams** [comment]
Very interesting, I like the way you have removed the dependency on Identity, but I see an issue. 

Lets say I have a Department many to many to AppUser (Users can be members of many departments, departments have many users).

I add a new DomainModel in Core, Department (with Id and Name).

On AppUser add an ICollection of Department, on Department I add an ICollection of AppUser.

I map them 

```
 modelBuilder.Entity<AppUser>()
                .HasMany(x => x.Departments)
                .WithMany(x => x.Users);
```

But wait, AppUser is not actually used in the EF Context, ApplicationIdentityUser is. So I add the corresponding fields to ApplicationIdentityUser, fix the mapping extensions to map them, and go back to my EFConfig:

```
 modelBuilder.Entity<ApplicationIdentityUser>()
                .HasMany(x => x.Department)
                .WithMany(x => x.Users); <-- Fail .. users is a list of AppUser, not ApplicationIdentityUser
```

Now my Core.DomainModels.Department class must reference ApplicationIdentityUser?

**Comment by wildest** [comment]
+1 to the post above. I'm also not sure how to use the AppUser / ApplicationUser as a Foreign Key on another model. Should we be using AppUser or ApplicationUser?

**Comment by imranbaloch** [comment]
Thanks I will check and let you know guys.

**Comment by wildest** [comment]
Hi @imranbaloch,
Did you happen to get a chance to look into this?

Thanks in advance,
Tom

**Comment by charanraj-golla** [comment]
Hi Imran, 
Thanks for providing a solution.
But as per the onion architecture, I should have all my domain entities only in the core project, which implies that I should be placing any additional property related to the user in the AppUser class.
As suggested by you, applying migration works if I put additional properties in the ApplicationIdentityUser class present in the Data project, but this is the part of infrastructure and not the core project .

A similar question is asked on stackoverflow : http://stackoverflow.com/questions/26580209/decoupling-asp-net-identity-from-the-core-domain-models-onion-architecture .He has mentioned the workaround used by him in the answer.

It would be great if you could help me come up with solution for the same.
