### ISSUE TITLE
How do we run this sample

### ISSUE THREAD

**Issue by ankitvyas** [imranbaloch/ASPNETIdentityWithOnion#6]
Hi there,

I downloaded zip file. It's compiling.
How do I execute this sample ?

When I try executing "ASPNETIdentityWithOnion.Web" project, it gives me error when I click on Register/Sign In because Bootstrapper dependencies are not loaded.

**Comment by imranbaloch** [comment]
Just set the build path of all projects to ../*.Web/bin and then re-build. Make sure that you have all the packages. 

Update: See below for deployment in better way.

**Comment by livertonoliveira** [comment]
How do I deploy this to Azure if I must set this bin config ?

**Comment by imranbaloch** [comment]
@livertonli12 I am also using Azure website to deploy my application using the onion architecture daily. I recommend that you should,

1) Keep the default build path as is and then unload/edit each project(_.csproj) except *_YouApp*\* .Web project and add these line just before </Project>,

```
<Target Name="AfterBuild">
  <ItemGroup>
    <_CustomFiles Include="..\YouApp.Bootstrapper\bin\$(Configuration)\**\*;" />
  </ItemGroup>
  <Copy SourceFiles="@(_CustomFiles)" DestinationFiles="@(_CustomFiles->'..\YouApp.Web\bin\%(Filename)%(Extension)')" SkipUnchangedFiles="false" />
</Target>
```

Note don't forget to replace **Bootstrapper** above with individual project. This will put all the required assemblies in the bin folder of **YouApp**.Web project. 

2) Open your deployment publish file(_.pubxml) from .> *_YouApp**.Web > Properties > PublishProfiles and add these lines there just before </Project>,,

```
<Target Name="CustomCollectFiles">
  <ItemGroup>
    <_CustomFiles Include="bin\**\*;" />
    <FilesForPackagingFromProject Include="%(_CustomFiles.Identity)">
      <DestinationRelativePath>bin\%(RecursiveDir)%(Filename)%(Extension)</DestinationRelativePath>
    </FilesForPackagingFromProject>
  </ItemGroup>
</Target>
<PropertyGroup>
  <CopyAllFilesToSingleFolderForPackageDependsOn>
    CustomCollectFiles;
    $(CopyAllFilesToSingleFolderForPackageDependsOn);
  </CopyAllFilesToSingleFolderForPackageDependsOn>

  <CopyAllFilesToSingleFolderForMsdeployDependsOn>
    CustomCollectFiles;
    $(CopyAllFilesToSingleFolderForPackageDependsOn);
  </CopyAllFilesToSingleFolderForMsdeployDependsOn>
</PropertyGroup>
```

3) Always Clean/Rebuild before publishing.

Hopefully this will help a lot.

**Comment by livertonoliveira** [comment]
Hi @imranbalch I'm glad that you have answered this faster.  

Fortunately I made this some different but also worked. I'll try your suggestion that makes more sense than mine and report later.  

I just placed one reference on my Web project at the end of Global.asax and called RegisterDepencies from there returning the ContainerBuilder after all I just build and proceeded. 

Btw, thank you very much,  your solution is helping me a lot.

**Comment by Yannick86** [comment]
Hello there,

I have everything working when running this in dev environment, but when I publish to file explorer I see only files from the web project. Aren't there supposed to be files coming from the bootstrapper project ( and others? ) ?

What are we supposed to do?

PS: When I run from VS2013 it creates the database and everything works perfect. All build paths of all projects go to the web project its bin folder.
