### ISSUE TITLE
ApplicationDbInitializer DropCreateDatabaseIfModelChanges

### ISSUE THREAD

**Issue by wildest** [imranbaloch/ASPNETIdentityWithOnion#7]
Hey,
Thanks for this sample, I'm working through it now!

I just noted something in the ApplicationDbInitializer class - In your comments you've called out "This example shows you how to create a new database if the Model changes" but then you've used the DropCreateDatabaseAlways option. I think this should be replaced with DropCreateDatabaseIfModelChanges ?

**Comment by imranbaloch** [comment]
Its up to the user. In my own application case I never use an ApplicationDbInitializer

**Comment by wildest** [comment]
I get that it's up to the user, I'm just saying that the comments seem to imply that the actual method being used (DropCreateDatabaseAlways) is actually DropCreateDatabaseIfModelChanges.

 // This is useful if you do not want to tear down the database each time you run the application.
// public class ApplicationDbInitializer : DropCreateDatabaseAlways<ApplicationDbContext>
// This example shows you how to create a new database if the Model changes
public class ApplicationDbInitializer : DropCreateDatabaseAlways<AspnetIdentityWithOnionContext>
