### ISSUE TITLE
How to query identity tables without using UserManager?

### ISSUE THREAD

**Issue by Yannick86** [imranbaloch/ASPNETIdentityWithOnion#8]
Hey guys,

I'm well aware of how to fetch users and roles by using the Role & User mangers like for example:
- _userManager.GetUsersAsync()
- _userManager.FindByIdAsync(id.Value)
- _roleManager.GetRoles()

But what if for example there would be another project. To keep it simple a normal console application and this application would need to be able to give a list of all the roles in the database. This project will not have a user or role manager. It should simply call the context and get all the roles.

How would you handle this wiith this architecture?

**Comment by imranbaloch** [comment]
Actually, in my web jobs, console application and windows services I am adding my own bootstrap that will bind the the projects together like we are doing in Bootstrap project. Sorry for late reply. These days I am busy with office choas.

**Comment by Yannick86** [comment]
Sorry, but what exactly do you mean by that? Could you give some sample code?
